# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-10 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ios_available_version', models.CharField(max_length=20)),
                ('ios_current_version', models.CharField(max_length=20)),
                ('ios_updateinfo', models.TextField()),
                ('ios_force_updateinfo', models.TextField(default='sorry, your app version is too low, please update, thx')),
                ('ios_url', models.CharField(max_length=200)),
            ],
        ),
    ]
