# Generated by Django 2.1.5 on 2019-02-22 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190222_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_last_login',
            new_name='last_login',
        ),
    ]
