# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-28 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('date_joined', models.DateTimeField(auto_created=True)),
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=11, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('nick_name', models.CharField(default='', max_length=30)),
                ('avatar', models.FileField(default='avatars/default.png', upload_to='avatars/', verbose_name='头像')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
