# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-28 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190628_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='nick_name',
            new_name='username',
        ),
    ]
