# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-28 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190527_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='create_time',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
