# Generated by Django 2.1.5 on 2019-02-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190222_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='nick_name',
        ),
        migrations.AddField(
            model_name='user',
            name='header_image_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='individuality_signature',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
