# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-02 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190628_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
