# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-16 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0002_auto_20190416_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='addr',
            field=models.CharField(default='昌平区天通苑西一区', max_length=200),
        ),
    ]
