# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-22 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0005_auto_20190422_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(related_name='books', to='bookmanager.Book'),
        ),
    ]
