# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-23 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0011_auto_20190423_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='detail',
        ),
        migrations.DeleteModel(
            name='AuthorDetail',
        ),
    ]
