# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-23 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0012_auto_20190423_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='book',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
