# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-23 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0013_auto_20190423_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
