# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-23 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0014_auto_20190423_1138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
