# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-23 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0016_auto_20190423_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorDetail',
        ),
    ]
