# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-23 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0019_auto_20190423_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('provice', models.CharField(max_length=32)),
                ('dept', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
