# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-23 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanager', '0020_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
