# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-22 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190422_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(),
        ),
    ]
