# Generated by Django 2.1.5 on 2019-01-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
