# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-27 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('ident', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('content', models.TextField(null=True)),
                ('status', models.IntegerField(default=0)),
                ('last_modified', models.DateTimeField()),
            ],
        ),
    ]
