# Generated by Django 2.1.5 on 2019-02-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='finish_date',
            field=models.DateField(default=None),
        ),
    ]
