# Generated by Django 2.1.5 on 2019-02-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_todos', '0004_auto_20190228_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='last_modified',
            field=models.DateTimeField(),
        ),
    ]
