# Generated by Django 2.1.5 on 2019-03-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_todos', '0006_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
