# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-28 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('ident', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('content', models.TextField(blank=True, default='')),
                ('status', models.IntegerField(default=0)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('ident', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time_counts', models.IntegerField(default=0)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_todos.Goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('ident', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=500)),
                ('group', models.IntegerField(default=0)),
                ('schedule_date', models.DateField()),
                ('finish_date', models.DateField(null=True)),
                ('remind_type', models.IntegerField(default=0)),
                ('remind_date', models.TimeField(null=True)),
                ('icon_index', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo')),
            ],
        ),
    ]
