# Generated by Django 2.1.5 on 2019-02-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('ident', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=500)),
                ('group', models.IntegerField(default=0)),
                ('schedule_date', models.DateField()),
                ('finish_date', models.DateField(blank=True)),
                ('remind_type', models.IntegerField(default=0)),
                ('remind_date', models.DateField(blank=True)),
                ('icon_index', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('finish_type', models.IntegerField(default=0)),
                ('user_id', models.IntegerField()),
                ('last_modified', models.IntegerField()),
            ],
        ),
    ]
