# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-27 10:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_todos', '0002_auto_20190527_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('ident', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time_counts', models.IntegerField(default=0)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_todos.Goal')),
            ],
        ),
    ]
