# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-31 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_todos', '0002_auto_20190731_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='content',
            field=models.TextField(default='', null=True),
        ),
    ]
