# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-22 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_todos', '0003_auto_20190731_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='remind_date',
            field=models.DateTimeField(null=True),
        ),
    ]
