# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-27 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_todos', '0003_timerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
