# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-28 08:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_todos', '0004_auto_20190527_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerecord',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='timerecord',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
