# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-22 01:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_todos', '0004_auto_20190822_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='icon_index',
            new_name='icon_type',
        ),
    ]
