# Generated by Django 2.1.5 on 2019-03-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_todos', '0005_auto_20190228_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('ident', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('content', models.BinaryField(null=True)),
                ('completeness', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('user_id', models.IntegerField()),
                ('last_modified', models.DateTimeField()),
            ],
        ),
    ]
