# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-04 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_todos', '0005_auto_20190528_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecord',
            name='ident',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
