# Generated by Django 2.1.5 on 2019-04-03 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_todos', '0008_goal_delete_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='finish_type',
        ),
    ]
