# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-12 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('screen_shot', models.FileField(default='screen_shot/default.png', upload_to='screen_shot/', verbose_name='缩略图')),
                ('resource_url', models.CharField(max_length=200)),
                ('up_count', models.IntegerField(default=0)),
                ('play_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoDetail',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='videos.Video')),
            ],
        ),
    ]
