# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-28 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=300)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('screen_shot', models.FileField(default='screen_shot/default.png', upload_to='screen_shot/', verbose_name='缩略图')),
                ('resource_url', models.CharField(max_length=500)),
                ('up_count', models.IntegerField(default=0)),
                ('play_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoBookmark',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('is_bookmark', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Video')),
            ],
            options={
                'verbose_name': 'Video-收藏',
                'verbose_name_plural': 'Video-收藏',
            },
        ),
        migrations.CreateModel(
            name='VideoDetail',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoPlay',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Video')),
            ],
            options={
                'verbose_name': 'Video-播放量',
                'verbose_name_plural': 'Video-播放量',
            },
        ),
        migrations.CreateModel(
            name='VideoThumbsUp',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Video')),
            ],
            options={
                'verbose_name': 'Video-点赞',
                'verbose_name_plural': 'Video-点赞',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='content',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='videos.VideoDetail'),
        ),
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Video'),
        ),
        migrations.AlterUniqueTogether(
            name='videothumbsup',
            unique_together=set([('video', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='videoplay',
            unique_together=set([('video', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='videobookmark',
            unique_together=set([('video', 'user')]),
        ),
    ]
