# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-27 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True)),
                ('url', models.CharField(max_length=1000)),
                ('pic_url', models.CharField(default='http://pm4u2yzfu.bkt.clouddn.com/default', max_length=1000)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
