# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-17 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoCollection',
            new_name='VideoBookmark',
        ),
        migrations.RenameField(
            model_name='videobookmark',
            old_name='is_collection',
            new_name='is_bookmark',
        ),
    ]
