# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-08 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='content_template',
            field=models.CharField(default='videos/video_detail.html', max_length=100),
        ),
    ]
