# Generated by Django 2.1.5 on 2019-01-25 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20190125_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='desc',
            new_name='detail',
        ),
    ]
