# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-22 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_content_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='screen_shot',
            field=models.FileField(default='/screen_shot/default.png', upload_to='screen_shot/', verbose_name='缩略图'),
        ),
    ]
