# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-12 08:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0002_comment_videothumbsup'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPlay',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Video')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='videothumbsup',
            unique_together=set([('video', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='videoplay',
            unique_together=set([('video', 'user')]),
        ),
    ]
