# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-02 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20190822_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Video2Tag',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Tag')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Video')),
            ],
            options={
                'verbose_name': '视频-标签',
                'verbose_name_plural': '视频-标签',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(through='videos.Video2Tag', to='videos.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='video2tag',
            unique_together=set([('video', 'tag')]),
        ),
    ]
