# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-13 02:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0003_auto_20190612_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCollection',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Video')),
            ],
            options={
                'verbose_name': 'Video-收藏',
                'verbose_name_plural': 'Video-收藏',
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelOptions(
            name='videoplay',
            options={'verbose_name': 'Video-播放量', 'verbose_name_plural': 'Video-播放量'},
        ),
        migrations.AlterModelOptions(
            name='videothumbsup',
            options={'verbose_name': 'Video-点赞', 'verbose_name_plural': 'Video-点赞'},
        ),
        migrations.AlterUniqueTogether(
            name='videocollection',
            unique_together=set([('video', 'user')]),
        ),
    ]
