# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-13 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20190613_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocollection',
            name='is_collection',
            field=models.BooleanField(default=True),
        ),
    ]
