# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-02 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_video_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
