# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-02 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_video_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
