# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-09 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='videobookmark',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
